export const APP_IMAGE = {
  splashBG: require('./SplashBG.png'),
  controler: require('./Controler.png'),
  HomeBG: require('./HomeBG.png'),
  FullController: require('./FullController.png'),
  LinearGradiant: require('./LinearGradiant.png'),
  Lineanimation: require('./Lineanimation.png'),
  RectangleBlur: require('./RectangleBlur.png'),
  BMW_1_1: require('./car1/BMW_1_1.jpg'),
  BMW_1_2: require('./car1/BMW_1_2.jpg'),
  BMW_1_3: require('./car1/BMW_1_3.jpg'),
  BMW_3_1: require('./car3/BMW_3_1.jpg'),
  BMW_3_2: require('./car3/BMW_3_2.jpg'),
  BMW_3_3: require('./car3/BMW_3_3.jpg'),
  BMW_4_1: require('./car4/BMW_4_1.jpg'),
  BMW_4_2: require('./car4/BMW_4_2.jpg'),
  BMW_4_3: require('./car4/BMW_4_2.jpg'),
  BMW_4_4: require('./car4/BMW_4_4.jpg'),
  BMW_5_1: require('./car5/BMW_5_1.jpg'),
  BMW_5_2: require('./car5/BMW_5_2.jpg'),
  BMW_6_1: require('./car6/BMW_6_1.jpg'),
  BMW_10_1: require('./car10/BMW_10_1.jpg'),
  BMW_10_2: require('./car10/BMW_10_2.jpg'),
  save: require('./save.png'),
};
